
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 03 11:52:25 CST 2012
//----------------------------------------------------

package javac.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int DIVIDE = 41;
  public static final int STRING_LITERAL = 4;
  public static final int LBRACKET = 22;
  public static final int CHAR = 10;
  public static final int INTEGER = 2;
  public static final int GREATER = 36;
  public static final int LPAREN = 24;
  public static final int CONTINUE = 19;
  public static final int INT = 8;
  public static final int MINUS = 39;
  public static final int LESS = 34;
  public static final int FOR = 16;
  public static final int CHARACTER = 5;
  public static final int RPAREN = 25;
  public static final int NOT = 43;
  public static final int SEMICOLON = 21;
  public static final int AND = 31;
  public static final int RECORD = 7;
  public static final int OR = 30;
  public static final int COMMA = 28;
  public static final int MULTIPLY = 40;
  public static final int PLUS = 38;
  public static final int ASSIGN = 29;
  public static final int IF = 13;
  public static final int DOT = 44;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int RBRACKET = 23;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MODULO = 42;
  public static final int NULL = 12;
  public static final int NEQ = 33;
  public static final int BREAK = 18;
  public static final int EQ = 32;
  public static final int LBRACE = 26;
  public static final int NATIVE = 6;
  public static final int ELSE = 14;
  public static final int WHILE = 15;
  public static final int LESS_EQ = 35;
  public static final int RBRACE = 27;
  public static final int STRING = 9;
  public static final int LRBRACKET = 20;
  public static final int GREATER_EQ = 37;
}

